--user
because pip3.7 install --upgrade pip gives
  Found existing installation: pip 19.2.3
    Uninstalling pip-19.2.3:
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip-19.2.3.dist-info/RECORD'
Consider using the `--user` option or check the permissions.

and sudo pip3.7 install --upgrade pip gives
WARNING: The directory '/Users/(user)/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.